
server:
  port: 8086
  servlet:
    context-path:
mybatis:
  type-aliases-package: com.newer.notes.domian
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT&useSSL=false
    username: root
    password: bbbb3333
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    serialization:
      indent_output: true
  logging:
    level:
      org.springframework.security: info
      com.newer.hospital.mapper: debug

